# Azure Pytest automation

# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    pip install pytest
    pip install pytest-cov
    pytest src
  displayName: 'Execute pytest tests'
